meta_product_name: "Mile'Up"
meta_title: "Mile'Up - Découvre le sport qui t'entoure !"
meta_description: "Trouvez facilement les équipements sportifs près de vous"
#meta_image: "logo.svg"      # Une image dans votre dossier app/assets/images/
