meta_product_name: "Mile'Up"
meta_title: "Dissensium - Obtenez des décisions plus créatives"
meta_description: "Trouvez facilement les équipements sportifs près de vous"
#meta_image: "logo.svg"      # Une image dans votre dossier app/assets/images/
